package seprojet ;

import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class TableauDuJeu extends javax.swing.JFrame {

    public String j1 ;
    public String j2 ;
    public int tour=0 ;
    public Plateau p ;
    Random rand ; 
    
    public TableauDuJeu() {
        initComponents();
        p = new Plateau() ;
        rand = new Random();
        c1.setEnabled(false);
        c2.setEnabled(false);
        c3.setEnabled(false);
        c4.setEnabled(false);
        c5.setEnabled(false);
        c6.setEnabled(false);
        c7.setEnabled(false);
    }
    
    private void putImageCoin(int i)//affichage des images au coin droit
    {
        Graphics2D ds = (Graphics2D)jPanel8.getGraphics();
        Image image = null ;
        try {
            image = ImageIO.read(new File("p"+i+".jpg"));
        } catch (IOException ex) {
            Logger.getLogger(TableauDuJeu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ds.drawImage(image, 0, 0, 59, 54, this) ;
    }
    
    private void putImage(int i , int lg , int cl)//affichage des images sur le plateau
    {
        Graphics2D ds = (Graphics2D)jPanel5.getGraphics();
        Image image = null ;
        try {
            image = ImageIO.read(new File("p"+i+".jpg"));
        } catch (IOException ex) {
            Logger.getLogger(TableauDuJeu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ds.drawImage(image, 50*cl, 50*lg, 50, 50, this) ;
    }
    
    private void putVictoire()//affichage de l'image de victoire
    {
        Graphics2D ds = (Graphics2D)jPanel8.getGraphics();
        Image image = null ;
        try {
            image = ImageIO.read(new File("coupe.png"));
        } catch (IOException ex) {
            Logger.getLogger(TableauDuJeu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ds.drawImage(image, 0 , 0 , 59, 54, this) ;
        c1.setEnabled(false);
        c2.setEnabled(false);
        c3.setEnabled(false);
        c4.setEnabled(false);
        c5.setEnabled(false);
        c6.setEnabled(false);
        c7.setEnabled(false);
    }
    
    private void putMatchNul()//affichage image lors d'un match null
    {
        Graphics2D ds = (Graphics2D)jPanel8.getGraphics();
        Image image = null ;
        try {
            image = ImageIO.read(new File("matchNul.png"));
        } catch (IOException ex) {
            Logger.getLogger(TableauDuJeu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        ds.drawImage(image, 0 , 0 , 59, 54, this) ;
        c1.setEnabled(false);
        c2.setEnabled(false);
        c3.setEnabled(false);
        c4.setEnabled(false);
        c5.setEnabled(false);
        c6.setEnabled(false);
        c7.setEnabled(false);
    }
    
    private void remplirPateau(Plateau p)//Simulation du contenu de la matrice à l'ecran !
    {
        for(int i=0 ; i<6 ; i++)
        {
            for(int j=0 ; j<7 ; j++)
            {
                if(p.pionAt(i, j)== 1)
                    putImage(1, i , j) ;
                else if(p.pionAt(i, j)== 2)
                    putImage(2, i , j) ; 
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomJoueur1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomJoueur2 = new javax.swing.JTextField();
        commencer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        msg = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        rejouer = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projet SE");
        setLocation(new java.awt.Point(450, 10));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        nomJoueur1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("JOUEUR 1");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("JOUEUR 2");

        nomJoueur2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        nomJoueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJoueur2ActionPerformed(evt);
            }
        });

        commencer.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        commencer.setText("Commencer");
        commencer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        commencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commencerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomJoueur1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(nomJoueur2))
                .addGap(18, 18, 18)
                .addComponent(commencer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commencer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(nomJoueur1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomJoueur2)
                            .addComponent(jLabel2))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        msg.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        msg.setForeground(new java.awt.Color(51, 51, 51));
        msg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        msg.setText("BIENVENUE AMIGOS");
        msg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(51, 51, 0));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("A");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("3");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("4");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("5");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("6");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("7");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("B");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 102, 0));
        jLabel12.setText("C");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 102, 0));
        jLabel13.setText("D");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 102, 0));
        jLabel14.setText("E");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 102, 0));
        jLabel15.setText("F");

        c1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 102, 0));
        c1.setText("I");
        c1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 102, 0));
        c2.setText("II");
        c2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 102, 0));
        c3.setText("III");
        c3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        c4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 102, 0));
        c4.setText("IV");
        c4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        c5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        c5.setForeground(new java.awt.Color(255, 102, 0));
        c5.setText("V");
        c5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        c6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        c6.setForeground(new java.awt.Color(255, 102, 0));
        c6.setText("VI");
        c6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });

        c7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        c7.setForeground(new java.awt.Color(255, 102, 0));
        c7.setText("VII");
        c7.setToolTipText("");
        c7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addGap(37, 37, 37)
                            .addComponent(jLabel6)
                            .addGap(44, 44, 44)
                            .addComponent(jLabel7)
                            .addGap(43, 43, 43)
                            .addComponent(jLabel8)
                            .addGap(42, 42, 42)
                            .addComponent(jLabel9)
                            .addGap(37, 37, 37)
                            .addComponent(jLabel10))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel11)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c6)
                        .addComponent(c7))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c1)
                        .addComponent(c2)
                        .addComponent(c3)
                        .addComponent(c4)
                        .addComponent(c5)))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));

        rejouer.setBackground(new java.awt.Color(255, 102, 0));
        rejouer.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        rejouer.setText("REJOUER");
        rejouer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rejouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejouerActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("Appuyez le bouton pour");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(rejouer, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rejouer)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void nomJoueur2ActionPerformed(java.awt.event.ActionEvent evt) {                                           

    }                                          

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if (!(p.placer(0,tour)))
        {
            c1.setEnabled(false);//desactivation du bouton qd la colonne est pleine
        }
        remplirPateau(p);//fonction d'affichage à l'ecran 
        switch(p.verif())
        {
            case 0 :
            {
                if(tour == 1)
                {
                    tour = 2 ;
                    msg.setText("C'est à "+j2+" de jouer !");
                }
                    
                else 
                {
                    tour = 1;
                    msg.setText("C'est à "+j1+" de jouer !");
                }
                putImageCoin(tour);
                break ;
            }
            case 1 :
            {
                msg.setText("Victoire pour "+j1+" !");
                putVictoire();
                break ;
            }
            case 2 :
            {
                msg.setText("Victoire pour "+j2+" !");
                putVictoire();
                break ;
            }
            case 3 :
            {
                msg.setText("Match nul !");
                putMatchNul();
                break ;
            }
        }
        p.afficherPalteau();   
    }                                  

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if (!(p.placer(1,tour)))
        {
            c2.setEnabled(false);//desactivation du bouton qd la colonne est pleine
        }
        remplirPateau(p);//fonction d'affichage à l'ecran 
        switch(p.verif())
        {
            case 0 :
            {
                if(tour == 1)
                {
                    tour = 2 ;
                    msg.setText("C'est à "+j2+" de jouer !");
                }
                    
                else 
                {
                    tour = 1;
                    msg.setText("C'est à "+j1+" de jouer !");
                }
                putImageCoin(tour);
                break ;
            }
            case 1 :
            {
                msg.setText("Victoire pour "+j1+" !");
                putVictoire();
                break ;
            }
            case 2 :
            {
                msg.setText("Victoire pour "+j2+" !");
                putVictoire();
                break ;
            }
            case 3 :
            {
                msg.setText("Match nul !");
                putMatchNul();
                break ;
            }
        }
        p.afficherPalteau();
    }                                  

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if (!(p.placer(2,tour)))
        {
            c3.setEnabled(false);//desactivation du bouton qd la colonne est pleine
        }
        remplirPateau(p);//fonction d'affichage à l'ecran 
        switch(p.verif())
        {
            case 0 :
            {
                if(tour == 1)
                {
                    tour = 2 ;
                    msg.setText("C'est à "+j2+" de jouer !");
                }
                    
                else 
                {
                    tour = 1;
                    msg.setText("C'est à "+j1+" de jouer !");
                }
                putImageCoin(tour);
                break ;
            }
            case 1 :
            {
                msg.setText("Victoire pour "+j1+" !");
                putVictoire();
                break ;
            }
            case 2 :
            {
                msg.setText("Victoire pour "+j2+" !");
                putVictoire();
                break ;
            }
            case 3 :
            {
                msg.setText("Match nul !");
                putMatchNul();
                break ;
            }
        }
        p.afficherPalteau();
    }                                  

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if (!(p.placer(3,tour)))
        {
            c4.setEnabled(false);//desactivation du bouton qd la colonne est pleine
        }
        remplirPateau(p);//fonction d'affichage à l'ecran 
        switch(p.verif())
        {
            case 0 :
            {
                if(tour == 1)
                {
                    tour = 2 ;
                    msg.setText("C'est à "+j2+" de jouer !");
                }
                    
                else 
                {
                    tour = 1;
                    msg.setText("C'est à "+j1+" de jouer !");
                }
                putImageCoin(tour);
                break ;
            }
            case 1 :
            {
                msg.setText("Victoire pour "+j1+" !");
                putVictoire();
                break ;
            }
            case 2 :
            {
                msg.setText("Victoire pour "+j2+" !");
                putVictoire();
                break ;
            }
            case 3 :
            {
                msg.setText("Match nul !");
                putMatchNul();
                break ;
            }
        }
        p.afficherPalteau();
    }                                  

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if (!(p.placer(4,tour)))
        {
            c5.setEnabled(false);//desactivation du bouton qd la colonne est pleine
        }
        remplirPateau(p);//fonction d'affichage à l'ecran 
        switch(p.verif())
        {
            case 0 :
            {
                if(tour == 1)
                {
                    tour = 2 ;
                    msg.setText("C'est à "+j2+" de jouer !");
                }
                    
                else 
                {
                    tour = 1;
                    msg.setText("C'est à "+j1+" de jouer !");
                }
                putImageCoin(tour);
                break ;
            }
            case 1 :
            {
                msg.setText("Victoire pour "+j1+" !");
                putVictoire();
                break ;
            }
            case 2 :
            {
                msg.setText("Victoire pour "+j2+" !");
                putVictoire();
                break ;
            }
            case 3 :
            {
                msg.setText("Match nul !");
                putMatchNul();
                break ;
            }
        }
        p.afficherPalteau();
    }                                  

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if (!(p.placer(5,tour)))
        {
            c6.setEnabled(false);//desactivation du bouton qd la colonne est pleine
        }
        remplirPateau(p);//fonction d'affichage à l'ecran 
        switch(p.verif())
        {
            case 0 :
            {
                if(tour == 1)
                {
                    tour = 2 ;
                    msg.setText("C'est à "+j2+" de jouer !");
                }
                    
                else 
                {
                    tour = 1;
                    msg.setText("C'est à "+j1+" de jouer !");
                }
                putImageCoin(tour);
                break ;
            }
            case 1 :
            {
                msg.setText("Victoire pour "+j1+" !");
                putVictoire();
                break ;
            }
            case 2 :
            {
                msg.setText("Victoire pour "+j2+" !");
                putVictoire();
                break ;
            }
            case 3 :
            {
                msg.setText("Match nul !");
                putMatchNul();
                break ;
            }
        }
        p.afficherPalteau();
    }                                  

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        if (!(p.placer(6,tour)))
        {
            c7.setEnabled(false);//desactivation du bouton qd la colonne est pleine
        }
        remplirPateau(p);//fonction d'affichage à l'ecran 
        switch(p.verif())
        {
            case 0 :
            {
                if(tour == 1)
                {
                    tour = 2 ;
                    msg.setText("C'est à "+j2+" de jouer !");
                }
                    
                else 
                {
                    tour = 1;
                    msg.setText("C'est à "+j1+" de jouer !");
                }
                putImageCoin(tour);
                break ;
            }
            case 1 :
            {
                msg.setText("Victoire pour "+j1+" !");
                putVictoire();
                break ;
            }
            case 2 :
            {
                msg.setText("Victoire pour "+j2+" !");
                putVictoire();
                break ;
            }
            case 3 :
            {
                msg.setText("Match nul !");
                putMatchNul();
                break ;
            }
        }
        p.afficherPalteau();
    }                                  

    private void commencerActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        j1=nomJoueur1.getText();
        j2=nomJoueur2.getText();
        if((j1.equals("") || j2.equals("")))
        {
            msg.setText("Entrer les noms des deux JOUEURS");
        }
        else
        {
            tour = rand.nextInt(2) + 1;
            if(tour == 1)
                msg.setText("C'est à "+j1+" de commencer !");
            else
                msg.setText("C'est à "+j2+" de commencer !");
            putImageCoin(tour);
            c1.setEnabled(true);
            c2.setEnabled(true);
            c3.setEnabled(true);
            c4.setEnabled(true);
            c5.setEnabled(true);
            c6.setEnabled(true);
            c7.setEnabled(true);
            
            commencer.setEnabled(false);
            
        }
        
        
    }                                         

    private void rejouerActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int rep = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment recommencer" ,"Nouvelle partie", JOptionPane.YES_NO_OPTION) ;
        if(rep == 0)
        {
            TableauDuJeu t = new TableauDuJeu() ;
            t.setVisible(true);
            this.dispose();
        }
        
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableauDuJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableauDuJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableauDuJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableauDuJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableauDuJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton commencer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField msg;
    private javax.swing.JTextField nomJoueur1;
    private javax.swing.JTextField nomJoueur2;
    private javax.swing.JButton rejouer;
    // End of variables declaration                   
}

